VuelaWebApp/VuelaWebApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VuelaWebApp.Models;

namespace VuelaWebApp.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Login(FormCollection form)
        {
            var email = form["correoElectronico"];
            var pass = form["contraseña"];
            if (ModelState.IsValid)
            {
                using (Entities db = new Entities())
                {
                    var u = db.cuenta.Where(a => a.usuario.Equals(email) && a.clave.Equals(pass)).FirstOrDefault();
                    if (u != null)//existe la cuenta
                    {
                        var tipo=db.tipoUsuario(email).FirstOrDefault();
                        if(tipo == "administrador")
                        {
                            empleado empleado = new empleado();
                            empleado.usuario = u.usuario;
                            Session["USER"] = empleado.usuario;
                            return RedirectToAction("About", "Home");
                        }
                        else if(tipo == "cliente")
                        {
                            cliente cliente = new cliente();
                            cliente.usuario = u.usuario;
                            Session["USER"] = cliente.usuario;
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            ViewBag.Error = "Error con su cuenta";
                        }
                    }
                    else
                    {
                        ViewBag.Error = "Correo o Password incorrectos. intentelo de nuevo.";
                    }
                }
            }
            return PartialView(form);
        }

        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Login", "Login");
        }
    }
}

VuelaWebApp/VuelaWebApp/Controllers/crearClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VuelaWebApp.Models;

namespace VuelaWebApp.Controllers
{
    public class crearClienteController : Controller
    {
        private Entities db = new Entities();

        // GET: crearCliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: crearCliente/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "usuario,nombre,clave,pasaporte,correo,paisResidencia")] crearCliente crearCliente)
        {
            if (ModelState.IsValid)
            {
                db.insertarCliente(crearCliente.usuario, crearCliente.clave, crearCliente.nombre, crearCliente.correo, crearCliente.paisResidencia, crearCliente.pasaporte);
                db.SaveChanges();
                return RedirectToAction("Login", "Login");
            }

            return View(crearCliente);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VuelaWebApp/VuelaWebApp/Views/Login/Login.cshtml
@{
    Layout = null;
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/Content/Login.css" rel="stylesheet" type="text/css" />
    <link href="Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" />
    <title>Iniciar Sesion</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Boostratp/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom fonts for this template -->
    <link href="~/Boostratp/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Boostratp/css/sb-admin.css" rel="stylesheet" />
</head>

<body>
    <form method="post" action="~/Login/Login">
        <div class="card card-container">
            <h4 class="text-center">Bienvenido a Vuela S.A.</h4>
            <hr />
            <img id="profile-img" class="profile-img-card" src="/images/Vuela-Logo.jpeg" />

            <span id="reauth-email" class="reauth-email"></span>

            <div class="form-group">
                <label for="username" class="cols-sm-2 control-label">Nombre de Usuario</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                        <input class="form-control" id="exampleInputEmail1" name="correoElectronico" aria-describedby="emailHelp" placeholder="Correo electronico">
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="password" class="cols-sm-2 control-label">Password</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="contraseña" placeholder="Contraseña">
                    </div>
                </div>
            </div>
            <hr />
            <button type="submit" class="btn btn-lg btn-info  btn-signin">Iniciar Sesion</button>
            <hr />
            <button type="submit" class="btn btn-lg btn-link">@Html.ActionLink("Registrarse", "Create", "crearCliente")</button>
            @if (ViewBag.Error != "")
            {
            <div class="text-danger form-group">
                @ViewBag.Error
            </div>
             }


            <!-- /form -->

        </div><!-- /card-container -->
    </form>
</body>
</html>